blank_issues_enabled: false
contact_links:
  - name: "ğŸ™‹ğŸ» Question"
    url: https://www.linkedin.com/in/ì˜ì—˜-ë°•-bb3ab42bb/
    about: ê°œë°œìì—ê²Œ ê¶êµ¼í•œ ì ì„ ì§ì ‘ ë¬¼ì–´ë³´ê³  ì‹¶ì–´ìš”. ğŸ¤”
